name: "Standalone"

on: [push]

jobs:
  execute:
    name: "Supported OS Build and Run"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operative-system: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v3
      -
        name: Dependencies
        run: |
          sudo apt update 
          sudo apt install build-essential
      -
        name: Build
        run: |
          cd /app
          ./build.sh
      -
        name: Run
        run: |
          cd /app
          ./Core